### ISSUE TITLE
請問如何新增譜面

### ISSUE THREAD

**Issue by youtoshihiko** [s890081tonyhsu/Unity-Rhythm-Game#1]
原本的檔案內無Songs資料夾
我自行下載了stepmania的譜面
請問要如何新增呢?

**Comment by s890081tonyhsu** [comment]
在專案底下開一個叫做Songs的資料夾（原本的我已經ignore掉了）。
然後直接把譜面連同資料夾丟到該資料夾內，結構大概會像這樣（跟StepMania的結構的差別少在資料夾分類）。

```
Project
├Assets
...
└Songs
    ├歌曲1
    ├歌曲2
    ...
    └歌曲n
        ├歌曲n.sm
        ├歌曲n.mp3
        ...
        └banner.jpg
```

如果這答案可以接受的話就麻煩你自己close囉

**Comment by youtoshihiko** [comment]
我照您的方式做
還是會出現 No songs are loaded.

**Comment by s890081tonyhsu** [comment]
有一點不確定因素可能要先告知
我選擇的譜面試保證在StepMania3.9版能正常讀取。能否給一張檔案目錄的截圖作為輔助說明呢？
